// Optional maintenance command; deployment still serves committed static files.
// Run after editing a source stylesheet. --check detects a stale generated file.
import { readFile, writeFile } from 'node:fs/promises';
const root = new URL('../', import.meta.url);
const sources = ['fonts', 'icons', 'style', 'hero', 'light-theme'];
const parts = await Promise.all(sources.map(async name =>
  `/* Source: assents/${name}.css */\n${await readFile(new URL(`assents/${name}.css`, root), 'utf8')}`));
const output = '/* Generated by node scripts/build-styles.mjs. Edit the source files. */\n' + parts.join('\n');
const target = new URL('assents/site.css', root);
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== output) throw new Error('Run node scripts/build-styles.mjs to refresh assents/site.css');
  console.log('Static production CSS is up to date.');
} else {
  await writeFile(target, output);
  console.log('Generated assents/site.css; no framework or deployment build required.');
}
